Repository tailor-cms/author, pull requests merged in 2024-08, with the labels that each got.

#144 Misc tweaks
  apps/backend/activity/activity.controller.js
  apps/backend/repository/repository.controller.js
  apps/backend/shared/publishing/helpers.js
  apps/backend/shared/storage/helpers.js
  apps/backend/shared/storage/providers/amazon.js
  apps/backend/shared/storage/storage.service.js
  packages/tailor-config-parser/src/schema-validation.js
Labels: ready for merge

#147 Bump node and setup action
  .eslintignore
  .github/actions/run/action.yml
  .github/actions/setup/action.yml
Labels: in-progress

#156 Remove store import
  packages/core-extensions/content-containers/page/src/edit/index.vue
Labels: code review

#160 Add schema meta inputs
  apps/frontend/app.vue
  apps/frontend/components/catalog/AddRepository/index.vue
  apps/frontend/components/common/MetaInput.vue
  apps/frontend/components/common/RepositoryNameField.vue
  apps/frontend/components/repository/Outline/CreateDialog/index.vue
  apps/frontend/package.json
  apps/frontend/pages/repository/[[id]]/root/settings/general.vue
  apps/frontend/plugins/vee-validate.ts
  apps/frontend/stores/repository.ts
  packages/core-components-next/src/components/FileInput.vue
  packages/tailor-config-parser/src/schema-processor.js
  pnpm-lock.yaml
  schemas/course-schema.js
Labels: code review

#167 Refactor create repo validation
  apps/frontend/components/catalog/AddRepository/index.vue
  apps/frontend/components/common/MetaInput.vue
  apps/frontend/package.json
  apps/frontend/plugins/vee-validate.ts
  packages/core-components-next/package.json
  pnpm-lock.yaml
Labels: code review

#170 Replace deprecated v-deep
  apps/frontend/components/editor/Sidebar/ActivityNavigation.vue
  apps/frontend/components/editor/Sidebar/ElementSidebar/index.vue
  apps/frontend/components/repository/Sidebar/index.vue
  apps/frontend/components/repository/Workflow/Sidebar/SidebarBody.vue
  apps/frontend/components/repository/Workflow/Sidebar/index.vue
  packages/core-components-next/src/components/Discussion/index.vue
Labels: ready for merge

#169 Bump ce-html, tweak toolbar
  apps/frontend/components/editor/Toolbar/DefaultToolbar.vue
  apps/frontend/components/editor/Toolbar/ElementToolbar.vue
  extensions/content-elements/package.json
  pnpm-lock.yaml
Labels: ready for merge

#175 Reset initial values upon profile save
  apps/frontend/components/user/UserInfo.vue
Labels: code review

#182 Fix catalog count, resolved comment error
  apps/backend/repository/repository.controller.js
  apps/frontend/stores/comments.ts
  packages/core-components-next/src/components/Discussion/Thread/Comment/CommentHeader.vue
Labels: code review

#191 Bump Multiple Choice Content Element
  extensions/content-elements/package.json
  pnpm-lock.yaml
Labels: code review

#193 Add missing configuration from diff
  apps/backend/package.json
  apps/frontend/components/editor/ActivityContent/ContainerList.vue
  apps/frontend/components/editor/Sidebar/index.vue
  apps/frontend/components/editor/Toolbar/ElementToolbar.vue
  apps/frontend/nuxt.config.ts
  apps/frontend/pages/repository/[[id]]/root/revisions.vue
  apps/frontend/stores/comments.ts
  extensions/content-elements/package.json
  packages/core-components-next/src/components/ContentElement.vue
  packages/core-components-next/src/components/Discussion/Thread/UnseenDivider.vue
  pnpm-lock.yaml
Labels: code review

#195 Bug Fixes
  apps/frontend/components/catalog/AddRepository/AIAssistance.vue
  apps/frontend/components/catalog/AddRepository/index.vue
  apps/frontend/components/repository/Workflow/Filters/Assignee.vue
  packages/core-components-next/src/components/FileInput.vue
  packages/core-components-next/src/components/RichTextEditor/index.vue
  packages/core-extensions/meta-inputs/meta-radio-group/src/EditMeta.vue
Labels: code review

#196 Update dependencies
  .env.dev
  .github/workflows/pr.yml
  apps/backend/config/server/kvStore.js
  apps/backend/package.json
  apps/backend/repository/feed/store.js
  apps/backend/shared/publishing/PublishingThrottler.js
  apps/backend/shared/request/mw.js
  apps/frontend/package.json
  docker-compose.dev.yaml
  infrastructure/package.json
  package.json
  packages/core-components-next/package.json
  packages/core-extensions/meta-inputs/meta-file/package.json
  packages/tailor-config-parser/package.json
  packages/tailor-config-shared/package.json
  packages/utils/package.json
  pnpm-lock.yaml
  tests/package.json
Labels: in-progress

#180 Add a11y E2E to PR workflow
  .github/workflows/pr.yml
Labels: in-progress
