Repository tailor-cms/author, pull requests merged in 2024-07, with the labels that each got.

#103 Increase E2E coverage
  apps/frontend/components/editor/Toolbar/ActivityActions.vue
  tests/specs/visual/editor.spec.ts
Labels: in-progress

#132 Fix condition fo resolving outline activities
  apps/backend/content-element/hooks.js
Labels: ready for merge

#134 Order element types by schema config
  packages/core-components-next/src/components/AddElement/index.vue
Labels: ready for merge

#131 Add schemas filtering
  .env.example
  Dockerfile
  apps/backend/repository/repository.controller.js
  apps/frontend/components/catalog/AddRepository/index.vue
  apps/frontend/nuxt.config.ts
  apps/frontend/pages/index.vue
  docs/dev/general/setup.md
  scripts/boot.js
Labels: ready for merge

#133 Remap uids upon importing and cloning course
  apps/backend/activity/activity.model.js
  apps/backend/content-element/content-element.model.js
  apps/backend/shared/transfer/default/index.js
  apps/backend/shared/transfer/default/processors.js
Labels: ready for merge

#137 Fix schema filtering
  Dockerfile
  apps/backend/config/server/general.js
  apps/backend/repository/repository.controller.js
  apps/frontend/components/repository/Sidebar/ActivityStatus.vue
  scripts/boot.js
Labels: ready for merge

#139 Include meta assets in the export
  apps/backend/shared/transfer/default/index.js
  apps/backend/shared/transfer/default/resolvers.js
Labels: code review

#138 Remove storage proxy codebase
  apps/backend/repository/proxy.js
  apps/backend/shared/storage/proxy/index.js
  apps/backend/shared/storage/proxy/mw.js
  apps/backend/shared/storage/proxy/providers/cloudfront.js
  apps/backend/shared/storage/proxy/providers/local.js
Labels: code review

#142 Prevent publishing detached pages
  apps/backend/activity/activity.controller.js
  apps/backend/activity/activity.model.js
  apps/frontend/composables/usePublishActivity.ts
Labels: ready for merge

#143 Pass references to the content element
  packages/core-components-next/src/components/ContainedContent.vue
  packages/core-components-next/src/components/ContentElement.vue
  packages/core-extensions/content-containers/page/src/edit/index.vue
  packages/tailor-interfaces/content-element.ts
Labels: code review
